# Generated by Django 5.2.4 on 2025-07-28 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('formally_employed', 'Formally Employed'), ('self_employed', 'Self-Employed'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='alumni',
            name='interest_academic',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Academic & Mentorship Interest Percentage'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='interest_career',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Career & Professional Development Interest Percentage'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='interest_giving_back',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Giving Back Interest Percentage'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='interest_networking',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Networking/Peer Engagement Interest Percentage'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='interest_stay_informed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Stay Informed Interest Percentage'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='current_employer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name of Organisation'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Designation'),
        ),
    ]
