# Generated by Django 5.2.4 on 2025-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumni_employment_status_alumni_interest_academic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='interest_academic',
            field=models.BooleanField(default=False, verbose_name='Academic & Mentorship'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='interest_career',
            field=models.BooleanField(default=False, verbose_name='Career & Professional Development'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='interest_giving_back',
            field=models.BooleanField(default=False, verbose_name='Giving Back'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='interest_networking',
            field=models.BooleanField(default=False, verbose_name='Networking/Peer Engagement'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='interest_stay_informed',
            field=models.BooleanField(default=False, verbose_name='Stay Informed'),
        ),
    ]
