# Generated by Django 4.2.24 on 2025-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alumnistory_sociallink_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='employment_other_details',
            field=models.TextField(blank=True, verbose_name='Please specify'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Maiden Name'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='other_programs',
            field=models.TextField(blank=True, help_text='List other programs obtained from MSU (optional)'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('formally_employed', 'Formally Employed'), ('self_employed', 'Self Employed'), ('unemployed', 'Not yet Employed'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
