# Generated by Django 4.2.24 on 2025-09-17 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_alumni_employment_other_details_alumni_maiden_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='graduation_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
