# Generated by Django 4.2.24 on 2025-09-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alter_alumni_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='interest_other',
            field=models.BooleanField(default=False, verbose_name='Other Interest'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='interest_other_details',
            field=models.TextField(blank=True, verbose_name='Please specify other interest'),
        ),
    ]
