# Generated by Django 4.2.24 on 2025-09-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_alumni_interest_other_alumni_interest_other_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.'), ('Dr', 'Dr.'), ('Prof', 'Prof.')], max_length=10),
        ),
    ]
