# Generated by Django 4.2.24 on 2025-09-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_alumni_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='date_of_engagement',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Engagement'),
        ),
    ]
