# Generated by Django 5.2.4 on 2025-08-19 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], unique=True)),
                ('title', models.CharField(help_text='Template title for this month', max_length=200)),
                ('message', models.TextField(help_text='Birthday message template. Use {name} for alumni name, {birthday_date} for birthday date.')),
                ('background_color', models.CharField(default='#f0f9ff', help_text='Hex color code for template background', max_length=7)),
                ('text_color', models.CharField(default='#1e40af', help_text='Hex color code for template text', max_length=7)),
                ('border_color', models.CharField(default='#3b82f6', help_text='Hex color code for template border', max_length=7)),
                ('emoji', models.CharField(default='🎉', help_text='Emoji to display with birthday message', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
    ]
